plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "org.jetbrains.kotlin.jvm" version "2.2.20"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"notenoughponies" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/neponies.aw")

}




repositories {
	maven { name = 'modmenu'; url = 'https://maven.terraformersmc.com/releases' }
	maven { name = 'minelp-snapshot'; url = 'https://repo.minelittlepony-mod.com/maven/snapshot' }
	maven { name = 'minelp-release'; url = 'https://repo.minelittlepony-mod.com/maven/release' }
	maven { url = 'https://maven.terraformersmc.com/releases/' }
	maven { url = 'https://maven.ladysnake.org/releases' }
	mavenCentral()
	maven { url = "https://cursemaven.com" }

	maven { name = "Modrinth"; url = "https://api.modrinth.com/maven" }

	maven {
		name = "entity-reach-attributes"
		url = "https://maven.jamieswhiteshirt.com/libs-release"
		content {
			includeGroup "com.jamieswhiteshirt"
		}
	}
}


dependencies {
	fileTree(dir: 'libs', include: ['*.jar']).each { File jar ->
		modImplementation files(jar)
	}

	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

	modApi("com.minelittlepony:minelittlepony:${project.minelp_version}") {
		exclude group: "net.fabricmc.fabric-api"
	}

	modImplementation "dev.emi:trinkets:${project.trinkets_version}"

	// Elytra Slot (Fabric) for 1.20.1 via Curse Maven
	modImplementation "curse.maven:elytra-slot-317716:5411569"

	// Unicopia
	modCompileOnly("maven.modrinth:unicopia:${project.unicopia_version}")

	modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:6.1.2"
	include "org.ladysnake.cardinal-components-api:cardinal-components-base:6.1.2"

	modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:6.1.2"
	include "org.ladysnake.cardinal-components-api:cardinal-components-entity:6.1.2"
}


// Task to copy mods into run/mods
tasks.register("syncMods", Copy) {
	def modsDir = file("$projectDir/run/mods")
	from {
		configurations.modImplementation.filter { it.name.matches(/(unicopia|elytra-slot).*\.jar/) }
	}
	into modsDir
	includeEmptyDirs = false

	eachFile { details ->
		def destFile = file("$modsDir/${details.name}")
		if (destFile.exists()) {
			details.exclude()
		}
	}

	doLast {
		println "Mods synced to run/mods"
	}
}

//tasks.named("classes") {
//	dependsOn(tasks.named("syncMods"))
//}


tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
	kotlinOptions {
		jvmTarget = "17"
	}
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
	withSourcesJar()
}


processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}

	from sourceSets.main.output
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
		// configure repositories for publishing if needed
	}
}
